# Generated by Django 5.0.7 on 2024-08-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_application', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_persons',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
